# Generated by Django 5.0.4 on 2024-05-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_checkemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
