# Generated by Django 5.0.4 on 2024-05-28 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModelGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category name"),
                ),
            ],
            options={
                "verbose_name_plural": "7.7.7 Category Guide Type",
                "db_table": "categoryGuide",
            },
        ),
        migrations.CreateModel(
            name="CategoryModelHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category name"),
                ),
            ],
            options={
                "verbose_name_plural": "3.3.3 Category Hotel Type",
                "db_table": "categoryHotel",
            },
        ),
        migrations.CreateModel(
            name="CategoryModelPacket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category name"),
                ),
            ],
            options={
                "verbose_name_plural": "6.6.6 Category Packet Type",
                "db_table": "categoryPacket",
            },
        ),
        migrations.CreateModel(
            name="CategoryModelRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category name"),
                ),
            ],
            options={
                "verbose_name_plural": "4.4.4 Category Restaurant Type",
                "db_table": "categoryRestaurant",
            },
        ),
        migrations.CreateModel(
            name="CategoryModelTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category name"),
                ),
            ],
            options={
                "verbose_name_plural": "5.5.5 Category Ticket Type",
                "db_table": "categoryTicket",
            },
        ),
        migrations.CreateModel(
            name="CategoryModelTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category name"),
                ),
            ],
            options={
                "verbose_name_plural": "2.2.2 Category Tour Type",
                "db_table": "categoryTour",
            },
        ),
        migrations.CreateModel(
            name="Sitemain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "1. Site main",
                "db_table": "site",
            },
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="media/")),
                ("description", models.TextField()),
                ("address", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.categorymodelguide",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "7. Guide",
                "db_table": "guide",
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField(default=0, verbose_name="price")),
                ("address", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.categorymodelhotel",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3. Hotel",
                "db_table": "hotel",
            },
        ),
        migrations.CreateModel(
            name="ImageGuideModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="image"
                    ),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.guide",
                        verbose_name="Guide",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "7.7. image guide list",
                "db_table": "ImageGuideModel",
            },
        ),
        migrations.CreateModel(
            name="ImageHotelModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="image"
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.hotel",
                        verbose_name="Hotel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3.3. image hotel list",
                "db_table": "ImageHotelModel",
            },
        ),
        migrations.CreateModel(
            name="Packet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("description", models.TextField()),
                ("address", models.TextField()),
                ("price", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.categorymodelpacket",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "6. Packet",
                "db_table": "packet",
            },
        ),
        migrations.CreateModel(
            name="ImagePacketModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="image"
                    ),
                ),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.packet",
                        verbose_name="Packet",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "6.6. image packet list",
                "db_table": "ImagePacketModel",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("description", models.TextField()),
                ("address", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.categorymodelrestaurant",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4. Restaurant",
                "db_table": "restaurant",
            },
        ),
        migrations.CreateModel(
            name="ImageRestaurantModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="image"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.restaurant",
                        verbose_name="Restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4.4. image restaurant list",
                "db_table": "ImageRestaurantModel",
            },
        ),
        migrations.CreateModel(
            name="ImagebannerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="image"
                    ),
                ),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.sitemain",
                        verbose_name="Sitemain",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "1.1. image banner list",
                "db_table": "ImageBannerModel",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("description", models.TextField()),
                ("address", models.TextField()),
                ("price", models.PositiveIntegerField(default=0, verbose_name="price")),
                ("brand", models.TextField(blank=True, null=True)),
                (
                    "carnumber",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="carnumber"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.categorymodelticket",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "5. ticket",
                "db_table": "Ticket",
            },
        ),
        migrations.CreateModel(
            name="ImageTicketModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="image"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.ticket",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "5.5. image ticket list",
                "db_table": "ImageTicketModel",
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="name", max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("description", models.TextField()),
                ("price", models.PositiveIntegerField(default=0, verbose_name="price")),
                ("address", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.categorymodeltour",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "2. Tour",
                "db_table": "tour",
            },
        ),
        migrations.CreateModel(
            name="ImageTourModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="media/", verbose_name="image"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourApi.tour",
                        verbose_name="Tour",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "2.2. image tour list",
                "db_table": "ImageTourModel",
            },
        ),
    ]
