# Generated by Django 5.0.6 on 2024-05-30 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tourApi", "0002_alter_tour_category_alter_tour_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tourApi.categorymodeltour",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="name",
            field=models.CharField(default="name", max_length=100),
        ),
    ]
