# Generated by Django 5.0.6 on 2024-05-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tourApi", "0004_alter_tour_category_alter_tour_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="packet",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="CategoryModelTour",
        ),
        migrations.RemoveField(
            model_name="imagebannermodel",
            name="banner",
        ),
        migrations.DeleteModel(
            name="CategoryModelGuide",
        ),
        migrations.DeleteModel(
            name="CategoryModelHotel",
        ),
        migrations.DeleteModel(
            name="CategoryModelPacket",
        ),
        migrations.DeleteModel(
            name="CategoryModelRestaurant",
        ),
        migrations.DeleteModel(
            name="CategoryModelTicket",
        ),
        migrations.DeleteModel(
            name="ImagebannerModel",
        ),
        migrations.DeleteModel(
            name="Sitemain",
        ),
    ]
